### ISSUE TITLE
Enhancement: suggest set when testing membership of a list or tuple

### ISSUE THREAD

**Issue by tekumara** [tonybaloney/perflint#42]
Suggest a set when checking membership of a list/tuple of hashable values.

eg:

```python
if fruit in {"orange", "apple"}:
```

rather than
```python
if fruit in ("orange", "apple"):
```
or
```python
if fruit in ["orange", "apple"]:
```

See also https://docs.sourcery.ai/Reference/Python/Default-Rules/collection-into-set/

**Comment by kotnen** [comment]
Could also suggest calling set on an iterable before checking membership?
e.g.
```py
for foo in iterable_of_foos:
    if foo in bar_iterable:
        do_something(foo)
```
->
```py
bar_set = set(bar_iterable)
for foo in iterable_of_foos:
    if foo in bar_set:
        do_something(foo)
```

**Comment by jenstroeger** [comment]
@tekumara that’s already an _optional_ checker ini pylint: [Set Membership checker](https://pylint.pycqa.org/en/latest/user_guide/checkers/extensions.html#pylint-extensions-set-membership).

**Comment by tekumara** [comment]
Oh right I don't use pylint so wasn't aware it had this check. If possible, it would still be nice for perflint to include this so all the performance related checks are together?

**Comment by tekumara** [comment]
Oh right thank you, I don't use pylint so wasn't aware it had this check. If possible, could perflint include this too so all the performance related checks are together?

**Comment by jenstroeger** [comment]
@tekumara have you also looked at `ruff`’s performance lint implementation [here](https://docs.astral.sh/ruff/rules/#perflint-perf)?

**Comment by tekumara** [comment]
oh yes! I'm using ruff rather than pylint or perflint directly 🙂

I thought to raise the issue here, as this is the upstream. Once implemented here, I'd hope ruff would implement it too.

**Comment by jenstroeger** [comment]
Well, I think @tonybaloney can find inspiration in `pylint`’s [set_membership.py](https://github.com/pylint-dev/pylint/blob/main/pylint/extensions/set_membership.py) module.

Although, looking at the inactivity of this repo over the past months I do worry that this package is getting stale… 🤔

**Comment by tonybaloney** [comment]
> Well, I think @tonybaloney can find inspiration in `pylint`’s [set_membership.py](https://github.com/pylint-dev/pylint/blob/main/pylint/extensions/set_membership.py) module.
> 
> 
> 
> Although, looking at the inactivity of this repo over the past months I do worry that this package is getting stale… 🤔

Sorry. I'm on a long overdue break. This is on my list for next week

**Comment by jenstroeger** [comment]
@tonybaloney oh that’s great to know 👍🏼  Enjoy your break!

**Comment by tonybaloney** [comment]
perflint is a plugin to pylint so you can run both together. I don't want to duplicate rules that already exist in pylint

**Comment by tonybaloney** [comment]
https://pylint.pycqa.org/en/latest/user_guide/messages/refactor/use-set-for-membership.html closing. thanks for the idea
